version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ticket_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  ticket-service:
    build: .
    container_name: ticket_service
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_Username: ${DB_Username}
      DB_Password: ${DB_Password}
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_R2DBC_USERNAME: ${DB_Username}
      SPRING_R2DBC_PASSWORD: ${DB_Password}
    depends_on:
      - postgres

volumes:
  pgdata:
