FROM eclipse-temurin:17-jdk-jammy AS build
WORKDIR /app
COPY pom.xml mvnw ./
COPY .mvn .mvn
COPY src ./src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080

ENV DB_Username=${DB_Username}
ENV DB_Password=${DB_Password}
ENV SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/${POSTGRES_DB}
ENV SPRING_R2DBC_USERNAME=${DB_Username}
ENV SPRING_R2DBC_PASSWORD=${DB_Password}

ENTRYPOINT ["java", "-jar", "app.jar"]
